USE test;

CREATE TABLE p_lots(
	name VARCHAR(30) NOT NULL,
	address VARCHAR(50),
    zone VARCHAR(25),
    PRIMARY KEY(name)
    );

CREATE TABLE spaces(
	sid INT NOT NULL,
    name VARCHAR(30) NOT NULL,
    space_type VARCHAR(5),
    PRIMARY KEY(name,sid),
    FOREIGN KEY (name) REFERENCES p_lots(name)
    ON DELETE CASCADE
);

CREATE TABLE NON_VISITOR_PERMITS (
    UNIQUE_PERMIT_ID VARCHAR(8) NOT NULL,
    CAR_COUNT INT default 1,
    ZONE_ID VARCHAR(2),
    LICENSE_NO VARCHAR(10),
    START_DATE DATE,
    EXPIRATION_DATE DATE,
    START_TIME TIME default '00:00',
    EXPIRATION_TIME TIME default '23:59',
    SPACE_TYPE VARCHAR(20),
    UNIV_ID VARCHAR(20),
    PRIMARY KEY(UNIQUE_PERMIT_ID,CAR_COUNT),
    CONSTRAINT check_number_cars CHECK(CAR_COUNT=1 or CAR_COUNT=2),
    CONSTRAINT check_space_type CHECK(SPACE_TYPE='R' or SPACE_TYPE ='V' or SPACE_TYPE='H' or SPACE_TYPE ='E')
    );

CREATE TABLE VISITOR_PERMITS (
	UNIQUE_PERMIT_ID VARCHAR(8) NOT NULL,
    LICENSE_NO VARCHAR(10),
    START_DATE DATE,
    EXPIRATION_DATE DATE,
    START_TIME TIME,
    DURATION TIME,
    EXPIRATION_TIME TIME,
    LOT VARCHAR(30),
    SPACE_TYPE VARCHAR(20),
    SPACE_NO INTEGER,
    PRIMARY KEY(UNIQUE_PERMIT_ID),
    CONSTRAINT check_visitor_space CHECK(SPACE_TYPE='R' or SPACE_TYPE ='V' or SPACE_TYPE='H' or SPACE_TYPE ='E'),
    FOREIGN KEY (LOT) REFERENCES p_lots(name)
    );

CREATE TABLE VEHICLE_INFO(
    LICENSE_NO VARCHAR(15),
    MANUFACTURER VARCHAR(15),
    MODEL VARCHAR(15),
    YEAR VARCHAR(4),
    COLOR VARCHAR(10),
    PRIMARY KEY(LICENSE_NO) );



CREATE TABLE CITATIONS(
    UNIQUE_CITATION_NUMBER INTEGER(5) AUTO_INCREMENT,
    LICENSE_NO VARCHAR(15),
    MODEL VARCHAR(15), 
    COLOR VARCHAR(10), 
    ISSUE_DATE DATE,
    LOT VARCHAR(15),
    TIME TIME,
    VIOLATION_CATEGORY VARCHAR(25),
    FEE INTEGER(2),
    DUE_DATE DATE, 
    STATUS VARCHAR(6) DEFAULT 'Unpaid',
    PRIMARY KEY(UNIQUE_CITATION_NUMBER),
    CONSTRAINT check_violation_category CHECK(VIOLATION_CATEGORY='Invalid Permit' OR VIOLATION_CATEGORY='Expired Permit' OR VIOLATION_CATEGORY='No Permit'),
    CONSTRAINT check_fee CHECK(FEE=20 OR FEE=25 OR FEE=40)
);



